IF NOT EXISTS(SELECT * FROM sysobjects WHERE name = 'MOVEMENTLOGS')
BEGIN

CREATE TABLE [dbo].MOVEMENTLOGS
(
    ID BIGINT PRIMARY KEY IDENTITY(1,1) NOT NULL,
    COURIERID BIGINT NOT NULL,
	LOGDATE DATETIME NOT NULL,
	LATITUDE FLOAT NOT NULL,
	LONGITUDE FLOAT NOT NULL,
	ISENTRANCE TINYINT NOT NULL,
	ENTEREDSTOREID BIGINT NULL
    )
END