IF NOT EXISTS (SELECT * FROM COURIERS WHERE NAME='Furkan Kalabalıkoğlu')
BEGIN
INSERT INTO COURIERS VALUES('Furkan Kalabalıkoğlu')
END

IF NOT EXISTS (SELECT * FROM COURIERS WHERE NAME='Ahmet Acar')
BEGIN
INSERT INTO COURIERS VALUES('Ahmet Acar')
END